# Store Type creation script using kfutil
# Generated by Doctool

Write-Host "Creating store type: F5-SL-REST"
kfutil store-types create F5-SL-REST

Write-Host "Creating store type: F5-WS-REST"
kfutil store-types create F5-WS-REST

Write-Host "Creating store type: F5-CA-REST"
kfutil store-types create F5-CA-REST

