# Creates all 3 store types via the Keyfactor Command REST API
# using PowerShell Invoke-RestMethod.
#
# Authentication (first matching method is used):
#   OAuth access token:   KEYFACTOR_AUTH_ACCESS_TOKEN
#   OAuth client creds:   KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET
#                         + KEYFACTOR_AUTH_TOKEN_URL
#   Basic auth (AD):      KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN
#
# Always required:
#   KEYFACTOR_HOSTNAME    Command hostname (e.g. my-command.example.com)
#
# Auto-generated by doctool generate-store-type-scripts — do not edit by hand.

if (-not $env:KEYFACTOR_HOSTNAME) {
    Write-Error "KEYFACTOR_HOSTNAME is required"
    exit 1
}

$uri     = "https://$($env:KEYFACTOR_HOSTNAME)/keyfactorapi/certificatestoretypes"
$headers = @{
    'Content-Type'               = "application/json"
    'x-keyfactor-requested-with' = "APIClient"
}

# ---------------------------------------------------------------------------
# Resolve auth
# ---------------------------------------------------------------------------
if ($env:KEYFACTOR_AUTH_ACCESS_TOKEN) {
    $headers['Authorization'] = "Bearer $($env:KEYFACTOR_AUTH_ACCESS_TOKEN)"
} elseif ($env:KEYFACTOR_AUTH_CLIENT_ID -and $env:KEYFACTOR_AUTH_CLIENT_SECRET -and $env:KEYFACTOR_AUTH_TOKEN_URL) {
    Write-Host "Fetching OAuth token..."
    $tokenBody = @{
        grant_type    = 'client_credentials'
        client_id     = $env:KEYFACTOR_AUTH_CLIENT_ID
        client_secret = $env:KEYFACTOR_AUTH_CLIENT_SECRET
    }
    $tokenResp = Invoke-RestMethod -Method Post -Uri $env:KEYFACTOR_AUTH_TOKEN_URL -Body $tokenBody
    $headers['Authorization'] = "Bearer $($tokenResp.access_token)"
} elseif ($env:KEYFACTOR_USERNAME -and $env:KEYFACTOR_PASSWORD -and $env:KEYFACTOR_DOMAIN) {
    $cred = [System.Convert]::ToBase64String(
        [System.Text.Encoding]::ASCII.GetBytes(
            "$($env:KEYFACTOR_USERNAME)@$($env:KEYFACTOR_DOMAIN):$($env:KEYFACTOR_PASSWORD)"))
    $headers['Authorization'] = "Basic $cred"
} else {
    Write-Error ("Authentication required. Set one of:`n" +
        "  KEYFACTOR_AUTH_ACCESS_TOKEN`n" +
        "  KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET + KEYFACTOR_AUTH_TOKEN_URL`n" +
        "  KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN")
    exit 1
}

function New-StoreType {
    param([string]$Name, [string]$Body)
    Write-Host "Creating $Name store type..."
    try {
        Invoke-RestMethod -Method Post -Uri $uri -Headers $headers -Body $Body -ContentType "application/json" | Out-Null
        Write-Host "  OK"
    } catch {
        Write-Warning "  FAILED: $($_.Exception.Message)"
    }
}

# ---------------------------------------------------------------------------
# F5-SL-REST — The server name or IP Address for the F5 device.
# ---------------------------------------------------------------------------
New-StoreType "F5-SL-REST" @'
{
  "Name": "F5 SSL Profiles REST",
  "ShortName": "F5-SL-REST",
  "Capability": "F5-SL-REST",
  "ServerRequired": true,
  "BlueprintAllowed": true,
  "CustomAliasAllowed": "Required",
  "PowerShell": false,
  "PrivateKeyAllowed": "Optional",
  "StorePathDescription": "Enter the name of the partition on the F5 device you wish to manage. This value is case sensitive, so if the partition name is \"Common\", it must be entered as \"Common\" and not \"common\",",
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": true,
    "StorePassword": {
      "Description": "Check \"No Password\" if you wish the private key of any added certificate to be set to Key Security Type \"Normal\". Enter a value (either a password or pointer to an installed PAM provider key for the password) to be used to encrypt the private key of any added certificate for Key Security Type of \"Password\".",
      "IsPAMEligible": true
    }
  },
  "Properties": [
    {
      "Name": "PrimaryNode",
      "DisplayName": "Primary Node",
      "Type": "String",
      "DependsOn": "PrimaryNodeOnlineRequired",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "PrimaryNodeCheckRetryWaitSecs",
      "DisplayName": "Primary Node Check Retry Wait Seconds",
      "Type": "String",
      "DependsOn": "PrimaryNodeOnlineRequired",
      "DefaultValue": "120",
      "Required": true
    },
    {
      "Name": "PrimaryNodeCheckRetryMax",
      "DisplayName": "Primary Node Check Retry Maximum",
      "Type": "String",
      "DependsOn": "PrimaryNodeOnlineRequired",
      "DefaultValue": "3",
      "Required": true
    },
    {
      "Name": "PrimaryNodeOnlineRequired",
      "DisplayName": "Primary Node Online Required",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "RemoveChain",
      "DisplayName": "Remove Chain on Add",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "False",
      "Required": false
    },
    {
      "Name": "IgnoreSSLWarning",
      "DisplayName": "Ignore SSL Warning",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "False",
      "Required": true
    },
    {
      "Name": "UseTokenAuth",
      "DisplayName": "Use Token Authentication",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true
    },
    {
      "Name": "SyncDevice",
      "DisplayName": "Sync To Device Group",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true
    },
    {
      "Name": "SyncDeviceGroup",
      "DisplayName": "Device Group",
      "Type": "String",
      "DependsOn": "SyncDevice",
      "DefaultValue": "DeviceGroup",
      "Required": true
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "true",
      "Required": true
    }
  ],
  "EntryParameters": [
    {
      "Name": "SSLProfiles",
      "DisplayName": "SSL Profiles",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DependsOn": "",
      "DefaultValue": "",
      "Options": "",
      "Description": "One to many comma delimited F5 SSL Profiles to bind the certificate to (new certificates ONLY)"
    }
  ]
}
'@

# ---------------------------------------------------------------------------
# F5-WS-REST — The server name or IP Address for the F5 device.
# ---------------------------------------------------------------------------
New-StoreType "F5-WS-REST" @'
{
  "Name": "F5 WS Profiles REST",
  "ShortName": "F5-WS-REST",
  "Capability": "F5-WS-REST",
  "ServerRequired": true,
  "BlueprintAllowed": true,
  "CustomAliasAllowed": "Forbidden",
  "PowerShell": false,
  "PrivateKeyAllowed": "Required",
  "StorePathDescription": "Enter the name of the partition on the F5 device you wish to manage. This value is case sensitive, so if the partition name is \"Common\", it must be entered as \"Common\" and not \"common\",",
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": false
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": false
  },
  "Properties": [
    {
      "Name": "PrimaryNode",
      "DisplayName": "Primary Node",
      "Type": "String",
      "DependsOn": "PrimaryNodeOnlineRequired",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "PrimaryNodeCheckRetryWaitSecs",
      "DisplayName": "Primary Node Check Retry Wait Seconds",
      "Type": "String",
      "DependsOn": "PrimaryNodeOnlineRequired",
      "DefaultValue": "120",
      "Required": true
    },
    {
      "Name": "PrimaryNodeCheckRetryMax",
      "DisplayName": "Primary Node Check Retry Maximum",
      "Type": "String",
      "DependsOn": "PrimaryNodeOnlineRequired",
      "DefaultValue": "3",
      "Required": true
    },
    {
      "Name": "PrimaryNodeOnlineRequired",
      "DisplayName": "Primary Node Online Required",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "IgnoreSSLWarning",
      "DisplayName": "Ignore SSL Warning",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "False",
      "Required": true
    },
    {
      "Name": "UseTokenAuth",
      "DisplayName": "Use Token Authentication",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "true",
      "Required": true
    }
  ],
  "EntryParameters": []
}
'@

# ---------------------------------------------------------------------------
# F5-CA-REST — The server name or IP Address for the F5 device.
# ---------------------------------------------------------------------------
New-StoreType "F5-CA-REST" @'
{
  "Name": "F5 CA Profiles REST",
  "ShortName": "F5-CA-REST",
  "Capability": "F5-CA-REST",
  "ServerRequired": true,
  "StorePathDescription": "Enter the name of the partition followed by the name of the bundle separated by a / (i.e. Common/BundleName). This value is case sensitive, so if the partition name is \"Common/BundleName\", it must be entered as \"Common/BundleName\" and not \"common/bundlename\",",
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": false
  },
  "PrivateKeyAllowed": "Forbidden",
  "JobProperties": [],
  "PowerShell": false,
  "BlueprintAllowed": true,
  "CustomAliasAllowed": "Required",
  "Properties": [
    {
      "Name": "PrimaryNode",
      "DisplayName": "Primary Node",
      "Type": "String",
      "DependsOn": "PrimaryNodeOnlineRequired",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "PrimaryNodeCheckRetryWaitSecs",
      "DisplayName": "Primary Node Check Retry Wait Seconds",
      "Type": "String",
      "DependsOn": "PrimaryNodeOnlineRequired",
      "DefaultValue": "120",
      "Required": true
    },
    {
      "Name": "PrimaryNodeCheckRetryMax",
      "DisplayName": "Primary Node Check Retry Maximum",
      "Type": "String",
      "DependsOn": "PrimaryNodeOnlineRequired",
      "DefaultValue": "3",
      "Required": true
    },
    {
      "Name": "PrimaryNodeOnlineRequired",
      "DisplayName": "Primary Node Online Required",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "IgnoreSSLWarning",
      "DisplayName": "Ignore SSL Warning",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "False",
      "Required": true
    },
    {
      "Name": "UseTokenAuth",
      "DisplayName": "Use Token Authentication",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "true",
      "Required": true
    }
  ],
  "EntryParameters": []
}
'@


Write-Host "Completed."
