name: Starter Workflow
on: [workflow_dispatch, push, pull_request]

jobs:
  call-create-github-release-workflow:
    uses: Keyfactor/actions/.github/workflows/github-release.yml@main

  call-assign-from-json-workflow:
    uses: Keyfactor/actions/.github/workflows/assign-env-from-json.yml@main

  call-dotnet-build-and-release-workflow:
    needs: [call-create-github-release-workflow, call-assign-from-json-workflow]
    uses: Keyfactor/actions/.github/workflows/dotnet-build-and-release.yml@main
    with:
      release_version: ${{ needs.call-create-github-release-workflow.outputs.release_version }}
      release_url: ${{ needs.call-create-github-release-workflow.outputs.release_url }}
      release_dir: ${{ needs.call-assign-from-json-workflow.outputs.release_dir }}

    secrets: 
      token: ${{ secrets.PRIVATE_PACKAGE_ACCESS }}

  call-generate-readme-workflow:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: Keyfactor/actions/.github/workflows/generate-readme.yml@main
    secrets:
      token: ${{ secrets.APPROVE_README_PUSH }}

  call-update-catalog-workflow:
    needs: call-assign-from-json-workflow
    if: needs.call-assign-from-json-workflow.outputs.update_catalog == 'True' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    uses: Keyfactor/actions/.github/workflows/update-catalog.yml@main
    secrets: 
      token: ${{ secrets.SDK_SYNC_PAT }}
