#!/usr/bin/env bash

# Creates all 3 store types via the Keyfactor Command REST API using curl.
#
# Authentication (first matching method is used):
#   OAuth access token:   KEYFACTOR_AUTH_ACCESS_TOKEN
#   OAuth client creds:   KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET
#                         + KEYFACTOR_AUTH_TOKEN_URL
#   Basic auth (AD):      KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN
#
# Always required:
#   KEYFACTOR_HOSTNAME    Command hostname (e.g. my-command.example.com)
#
# Auto-generated by doctool generate-store-type-scripts — do not edit by hand.

if [ -z "${KEYFACTOR_HOSTNAME}" ]; then
    echo "ERROR: KEYFACTOR_HOSTNAME is required"
    exit 1
fi

BASE_URL="https://${KEYFACTOR_HOSTNAME}/keyfactorapi"

# ---------------------------------------------------------------------------
# Resolve auth
# ---------------------------------------------------------------------------
if [ -n "${KEYFACTOR_AUTH_ACCESS_TOKEN}" ]; then
    BEARER_TOKEN="${KEYFACTOR_AUTH_ACCESS_TOKEN}"
elif [ -n "${KEYFACTOR_AUTH_CLIENT_ID}" ] && [ -n "${KEYFACTOR_AUTH_CLIENT_SECRET}" ] && [ -n "${KEYFACTOR_AUTH_TOKEN_URL}" ]; then
    echo "Fetching OAuth token..."
    BEARER_TOKEN=$(curl -s -X POST "${KEYFACTOR_AUTH_TOKEN_URL}" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        --data-urlencode "grant_type=client_credentials" \
        --data-urlencode "client_id=${KEYFACTOR_AUTH_CLIENT_ID}" \
        --data-urlencode "client_secret=${KEYFACTOR_AUTH_CLIENT_SECRET}" | jq -r '.access_token')
    if [ -z "${BEARER_TOKEN}" ] || [ "${BEARER_TOKEN}" = "null" ]; then
        echo "ERROR: Failed to fetch OAuth token from ${KEYFACTOR_AUTH_TOKEN_URL}"
        exit 1
    fi
elif [ -n "${KEYFACTOR_USERNAME}" ] && [ -n "${KEYFACTOR_PASSWORD}" ] && [ -n "${KEYFACTOR_DOMAIN}" ]; then
    BEARER_TOKEN=""
else
    echo "ERROR: Authentication required. Set one of:"
    echo "  KEYFACTOR_AUTH_ACCESS_TOKEN"
    echo "  KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET + KEYFACTOR_AUTH_TOKEN_URL"
    echo "  KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN"
    exit 1
fi

if [ -n "${BEARER_TOKEN}" ]; then
    CURL_AUTH=("-H" "Authorization: Bearer ${BEARER_TOKEN}")
else
    CURL_AUTH=("-u" "${KEYFACTOR_USERNAME}@${KEYFACTOR_DOMAIN}:${KEYFACTOR_PASSWORD}")
fi

create_store_type() {
    local name="$1"
    local body="$2"
    echo "Creating ${name} store type..."
    response=$(curl -s -o /dev/null -w "%{http_code}" \
        -X POST "${BASE_URL}/certificatestoretypes" \
        -H "Content-Type: application/json" \
        -H "x-keyfactor-requested-with: APIClient" \
        "${CURL_AUTH[@]}" \
        -d "${body}")
    if [ "$response" = "200" ] || [ "$response" = "201" ]; then
        echo "  OK (HTTP ${response})"
    else
        echo "  FAILED (HTTP ${response})"
    fi
}

# ---------------------------------------------------------------------------
# F5-SL-REST — The server name or IP Address for the F5 device.
# ---------------------------------------------------------------------------
create_store_type "F5-SL-REST" '{
  "Name": "F5 SSL Profiles REST",
  "ShortName": "F5-SL-REST",
  "Capability": "F5-SL-REST",
  "ServerRequired": true,
  "BlueprintAllowed": true,
  "CustomAliasAllowed": "Required",
  "PowerShell": false,
  "PrivateKeyAllowed": "Optional",
  "StorePathDescription": "Enter the name of the partition on the F5 device you wish to manage. This value is case sensitive, so if the partition name is \"Common\", it must be entered as \"Common\" and not \"common\",",
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": true,
    "StorePassword": {
      "Description": "Check \"No Password\" if you wish the private key of any added certificate to be set to Key Security Type \"Normal\". Enter a value (either a password or pointer to an installed PAM provider key for the password) to be used to encrypt the private key of any added certificate for Key Security Type of \"Password\".",
      "IsPAMEligible": true
    }
  },
  "Properties": [
    {
      "Name": "PrimaryNode",
      "DisplayName": "Primary Node",
      "Type": "String",
      "DependsOn": "PrimaryNodeOnlineRequired",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "PrimaryNodeCheckRetryWaitSecs",
      "DisplayName": "Primary Node Check Retry Wait Seconds",
      "Type": "String",
      "DependsOn": "PrimaryNodeOnlineRequired",
      "DefaultValue": "120",
      "Required": true
    },
    {
      "Name": "PrimaryNodeCheckRetryMax",
      "DisplayName": "Primary Node Check Retry Maximum",
      "Type": "String",
      "DependsOn": "PrimaryNodeOnlineRequired",
      "DefaultValue": "3",
      "Required": true
    },
    {
      "Name": "PrimaryNodeOnlineRequired",
      "DisplayName": "Primary Node Online Required",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "RemoveChain",
      "DisplayName": "Remove Chain on Add",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "False",
      "Required": false
    },
    {
      "Name": "IgnoreSSLWarning",
      "DisplayName": "Ignore SSL Warning",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "False",
      "Required": true
    },
    {
      "Name": "UseTokenAuth",
      "DisplayName": "Use Token Authentication",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "true",
      "Required": true
    }
  ],
  "EntryParameters": [
    {
      "Name": "SSLProfiles",
      "DisplayName": "SSL Profiles",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DependsOn": "",
      "DefaultValue": "",
      "Options": "",
      "Description": "One to many comma delimited F5 SSL Profiles to bind the certificate to (new certificates ONLY)"
    }
  ]
}'

# ---------------------------------------------------------------------------
# F5-WS-REST — The server name or IP Address for the F5 device.
# ---------------------------------------------------------------------------
create_store_type "F5-WS-REST" '{
  "Name": "F5 WS Profiles REST",
  "ShortName": "F5-WS-REST",
  "Capability": "F5-WS-REST",
  "ServerRequired": true,
  "BlueprintAllowed": true,
  "CustomAliasAllowed": "Forbidden",
  "PowerShell": false,
  "PrivateKeyAllowed": "Required",
  "StorePathDescription": "Enter the name of the partition on the F5 device you wish to manage. This value is case sensitive, so if the partition name is \"Common\", it must be entered as \"Common\" and not \"common\",",
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": false
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": false
  },
  "Properties": [
    {
      "Name": "PrimaryNode",
      "DisplayName": "Primary Node",
      "Type": "String",
      "DependsOn": "PrimaryNodeOnlineRequired",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "PrimaryNodeCheckRetryWaitSecs",
      "DisplayName": "Primary Node Check Retry Wait Seconds",
      "Type": "String",
      "DependsOn": "PrimaryNodeOnlineRequired",
      "DefaultValue": "120",
      "Required": true
    },
    {
      "Name": "PrimaryNodeCheckRetryMax",
      "DisplayName": "Primary Node Check Retry Maximum",
      "Type": "String",
      "DependsOn": "PrimaryNodeOnlineRequired",
      "DefaultValue": "3",
      "Required": true
    },
    {
      "Name": "PrimaryNodeOnlineRequired",
      "DisplayName": "Primary Node Online Required",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "IgnoreSSLWarning",
      "DisplayName": "Ignore SSL Warning",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "False",
      "Required": true
    },
    {
      "Name": "UseTokenAuth",
      "DisplayName": "Use Token Authentication",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "true",
      "Required": true
    }
  ],
  "EntryParameters": []
}'

# ---------------------------------------------------------------------------
# F5-CA-REST — The server name or IP Address for the F5 device.
# ---------------------------------------------------------------------------
create_store_type "F5-CA-REST" '{
  "Name": "F5 CA Profiles REST",
  "ShortName": "F5-CA-REST",
  "Capability": "F5-CA-REST",
  "ServerRequired": true,
  "StorePathDescription": "Enter the name of the partition followed by the name of the bundle separated by a / (i.e. Common/BundleName). This value is case sensitive, so if the partition name is \"Common/BundleName\", it must be entered as \"Common/BundleName\" and not \"common/bundlename\",",
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": false
  },
  "PrivateKeyAllowed": "Forbidden",
  "JobProperties": [],
  "PowerShell": false,
  "BlueprintAllowed": true,
  "CustomAliasAllowed": "Required",
  "Properties": [
    {
      "Name": "PrimaryNode",
      "DisplayName": "Primary Node",
      "Type": "String",
      "DependsOn": "PrimaryNodeOnlineRequired",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "PrimaryNodeCheckRetryWaitSecs",
      "DisplayName": "Primary Node Check Retry Wait Seconds",
      "Type": "String",
      "DependsOn": "PrimaryNodeOnlineRequired",
      "DefaultValue": "120",
      "Required": true
    },
    {
      "Name": "PrimaryNodeCheckRetryMax",
      "DisplayName": "Primary Node Check Retry Maximum",
      "Type": "String",
      "DependsOn": "PrimaryNodeOnlineRequired",
      "DefaultValue": "3",
      "Required": true
    },
    {
      "Name": "PrimaryNodeOnlineRequired",
      "DisplayName": "Primary Node Online Required",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "IgnoreSSLWarning",
      "DisplayName": "Ignore SSL Warning",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "False",
      "Required": true
    },
    {
      "Name": "UseTokenAuth",
      "DisplayName": "Use Token Authentication",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "true",
      "Required": true
    }
  ],
  "EntryParameters": []
}'


echo "Completed."
