#!/bin/bash
# Store Type creation script using kfutil
# Generated by Doctool

set -e

echo "Creating store type: F5-SL-REST"
kfutil store-types create F5-SL-REST

echo "Creating store type: F5-WS-REST"
kfutil store-types create F5-WS-REST

echo "Creating store type: F5-CA-REST"
kfutil store-types create F5-CA-REST

